### PR TITLE
consider comment lines to begin with spaces or tabs too

### PR DESCRIPTION
**Pull request by rsilraf**
for me it is interesting to also remove comment lines that do not start exactly with # character.

### CODE REVIEW

**Comment by Aralhach** [comment]
Great idea!! I forgot to consider that case... thank you very much!! :) :)

**Comment by rsilraf** [comment]
I've just did a new commit on my forked project.
It includes **aggressive (-A)**  option, which basically tries to put **more stuff on same line** and also handles obfuscation on missing use cases such as in post/pre increment statemens, _e.g.: (( myvar++ )) or (( --myvar ))_.
It handled correctly my use case where I had _multiline gawk, expect and SQL code_ inline with my shell scripts.
Most manipulation are done via **sed** script after output file is completed. I wonder if would be possible to do it directly on perl, as my perl knowledge is very bare-bones. :(
Best regards.

**Comment by Aralhach** [comment]
Wow!! Nice work!! I'll review it as soon as I can :) I've been swamped with work this week :( I really appreciate your time and the work you've put into this project! Thanks!!

**Comment by rsilraf** [comment]
hi, no problem, do as you can.
I've got an issue on a line containing only a grep command enclosuded by '|'s, it was unable to change variable name:

`function f(){`
**`a10=$1`**
`sed '.......' |`
`gawk -F\n 'BEGIN {`
`... some lines of code in here`
`}' | egrep -i`**"${search}"**`|`      <------   it should have changed to ${a10}
`while read ......`

but I've also found a workaround for that, that is to break line after the preceding egrep '|' :
`... some lines of awk code in here`
`}' |` <------    breaking line here
`egrep -i`**"${a10}"**`|`       <------  then it worked
`while read ......`

as a conclusion, it is always recommended to take a look and test the script after the obfuscation, be it 'normal' or 'aggressive' modes.
Even (perhaps still :) ) not being able to put all that is possible in one line, the script does a good job.
thanks.

**Comment by Aralhach** [comment]
The reason the substitution is not happening in that case is because right before the `egrep`, you have a `'` that closes the `'` on the gawk call, but the regex sees it as the first `'` in the line, which disables substitution for anything inside single quotes.

I absolutely agree with you that one needs to check the script before deploying it.  I would like to at some point make it more rich and capable of processing the language as such, which would give much richer substitutions.

**Pull request merged**
